### ISSUE TITLE
engine_pkcs11 segfault in EC operations with SafeNet

### ISSUE THREAD

**Issue by aalba6675** [OpenSC/libp11#209]
Using SafeNet as OpenSSL engine via engine_pkcs11: EC operations are segfaulting with EC keys when no public key is on token. Using the gem engine from SafeNet works correctly.

It would appear that an EC public key with the same ID is required.

RSA operations work when there is no corresponding public key on token.

```
# rpm -q openssl engine_pkcs11
openssl-1.0.2k-8.el7.x86_64
engine_pkcs11-0.4.7-1.el7.x86_64
```

Failed key
```
openssl pkey -pubout -engine pkcs11 -inform engine -in 'pkcs11:token=WEBTOKEN;object=webkey_1'
luna_get_conf_path: "/etc/Chrystoki.conf"
LibPath64: "/usr/lib/libCryptoki2_64.so"
EnableEcdsaEx: "1"
LogLevel: "7"
DisableDsa: "0"
DisableEcdsa: "0"
DisableRand: "0"
DisableSessionCache: "1"
DisablePublicCrypto: "1"
EnableLoadPrivKey: "1"
EnableLoadPubKey: "1"
EnableLoginInit: "1"
EnableRsaGenKeyPair: "1"
EnableDsaGenKeyPair: "1"
EnableRsaSignVerify: "1"
engine "pkcs11" set.
Missing CKA_ALWAYS_AUTHENTICATE attribute
Segmentation fault
```

**Comment by aalba6675** [comment]
p11tool shows the difference in keys:
```
Object 1:
        URL: pkcs11:token=WEBTOKEN;object=webkey_1;type=private
        Type: Private key
        Label: webkey_1
        Flags: CKA_WRAP/UNWRAP; CKA_PRIVATE; CKA_SENSITIVE; 
        ID: 00:00:01:5e:88:d2:7e:b8

Object 2:
        URL: pkcs11:token=WEBTOKEN;object=webkey_2;type=private
        Type: Private key
        Label: webkey_2
        Flags: CKA_PRIVATE; CKA_SENSITIVE; 
        ID: 50:00:00
```

**Comment by aalba6675** [comment]
bt:

```
Program received signal SIGSEGV, Segmentation fault.
EC_POINT_point2oct (group=0x7acfc0, point=0x0, form=POINT_CONVERSION_UNCOMPRESSED, buf=buf@entry=0x0, len=len@entry=0, ctx=ctx@entry=0x0) at ec_oct.c:144
144         if (group->meth != point->meth) {
(gdb) bt
#0  EC_POINT_point2oct (group=0x7acfc0, point=0x0, form=POINT_CONVERSION_UNCOMPRESSED, buf=buf@entry=0x0, len=len@entry=0, ctx=ctx@entry=0x0) at ec_oct.c:144
#1  0x00007ffff6e85a1b in i2o_ECPublicKey (a=a@entry=0x7adc90, out=out@entry=0x0) at ec_asn1.c:1300
#2  0x00007ffff6e881c2 in eckey_pub_encode (pk=0x7ae1b0, pkey=<optimized out>) at ec_ameth.c:120
#3  0x00007ffff6ee122b in X509_PUBKEY_set (x=0x7add48, pkey=pkey@entry=0x7aeb50) at x_pubkey.c:101
#4  0x00007ffff6f01886 in X509_REQ_set_pubkey (x=x@entry=0x7adcf0, pkey=pkey@entry=0x7aeb50) at x509rset.c:84
#5  0x000000000041ec01 in make_REQ (chtype=4097, attribs=1, multirdn=0, subj=<optimized out>, pkey=0x7aeb50, req=<optimized out>) at req.c:1105
#6  req_main (argc=<optimized out>, argv=<optimized out>) at req.c:770
#7  0x000000000041a7a8 in do_cmd (prog=prog@entry=0x6a3dd0, argc=argc@entry=10, argv=0x7fffffffe530) at openssl.c:477
#8  0x000000000041a49e in main (Argc=10, Argv=<optimized out>) at openssl.c:371
```

**Comment by aalba6675** [comment]
Artifact of SafeNet PKCS#11 implementation: it does not need the EC public key as a separate object; the private key object contains EC_PARAMS and EC_POINT. This is not standards compliant.
